import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'

const root = fileURLToPath(new URL('..', import.meta.url))

// bytes, gzipped
const BUDGETS = {
  'dist/button/index.js': 300,
  'dist/button/styled.js': 350,
  'dist/button/a11y.js': 700,
  'dist/dialog/index.js': 300,
  'dist/dialog/styled.js': 350,
  'dist/dialog/a11y.js': 1500,
  'dist/combobox/a11y.js': 4000,
}
const COMBINED = { 'all a11y entries': { max: 7000, match: /a11y\.js$/ } }
const CSS_BUDGET = 3000

const gz = (f) => gzipSync(readFileSync(join(root, f))).length
const rows = []
const errors = []

for (const [file, max] of Object.entries(BUDGETS)) {
  if (!existsSync(join(root, file))) continue // not built yet
  const size = gz(file)
  rows.push({ file, size, max })
  if (size > max) errors.push(`${file}: ${size} B gz exceeds budget ${max} B`)
}

for (const [label, { max, match }] of Object.entries(COMBINED)) {
  const files = rows.filter((r) => match.test(r.file))
  if (!files.length) continue
  const total = files.reduce((n, r) => n + r.size, 0)
  rows.push({ file: label, size: total, max })
  if (total > max) errors.push(`${label}: ${total} B gz exceeds budget ${max} B`)
}

if (existsSync(join(root, 'dist/styles.css'))) {
  const size = gz('dist/styles.css')
  rows.push({ file: 'dist/styles.css', size, max: CSS_BUDGET })
  if (size > CSS_BUDGET) errors.push(`dist/styles.css: ${size} B gz exceeds ${CSS_BUDGET} B`)
}

const md = [
  '# Bundle sizes',
  '',
  'Generated by `npm run build`. Gzipped, React external. Do not edit by hand.',
  '',
  '| Entry | Gzipped | Budget | |',
  '|---|---:|---:|---|',
  ...rows.map((r) => `| \`${r.file}\` | ${r.size} B | ${r.max} B | ${r.size <= r.max ? 'ok' : 'OVER'} |`),
  '',
].join('\n')

writeFileSync(join(root, 'SIZES.md'), md)
console.log(md)

if (errors.length) {
  console.error('\nsize budget FAILED:\n' + errors.map((e) => `  - ${e}`).join('\n') + '\n')
  process.exit(1)
}
