import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'

const root = fileURLToPath(new URL('..', import.meta.url))

// bytes, gzipped
const BUDGETS = {
  'dist/button/index.js': 300,
  'dist/button/styled.js': 350,
  'dist/button/a11y.js': 700,
  'dist/dialog/index.js': 300,
  'dist/dialog/styled.js': 350,
  'dist/dialog/a11y.js': 1500,
  // Added when scripts/check-complete.js noticed these two had never had
  // a budget at all: combobox was the first component built and only its
  // a11y tier was ever listed.
  'dist/combobox/index.js': 700,
  'dist/combobox/styled.js': 150,
  'dist/combobox/a11y.js': 4000,
  'dist/input/index.js': 250,
  'dist/input/styled.js': 150,
  'dist/input/a11y.js': 700,
  'dist/checkbox/index.js': 250,
  'dist/checkbox/styled.js': 150,
  'dist/checkbox/a11y.js': 850,
  'dist/radio/index.js': 200,
  'dist/radio/styled.js': 150,
  'dist/radio/a11y.js': 800,
  'dist/select/index.js': 300,
  'dist/select/styled.js': 150,
  'dist/select/a11y.js': 700,
  'dist/accordion/index.js': 450,
  'dist/accordion/styled.js': 150,
  'dist/accordion/a11y.js': 250,
  'dist/textarea/index.js': 250,
  'dist/textarea/styled.js': 150,
  'dist/textarea/a11y.js': 700,
  'dist/switch/index.js': 250,
  'dist/switch/styled.js': 150,
  'dist/switch/a11y.js': 600,
  'dist/popover/index.js': 500,
  'dist/popover/styled.js': 200,
  'dist/popover/a11y.js': 600,
  'dist/tabs/index.js': 700,
  'dist/tabs/styled.js': 150,
  'dist/tabs/a11y.js': 1400,
  'dist/alert/index.js': 250,
  'dist/alert/styled.js': 150,
  'dist/alert/a11y.js': 400,
  'dist/progress/index.js': 250,
  'dist/progress/styled.js': 150,
  'dist/progress/a11y.js': 700,
  'dist/slider/index.js': 250,
  'dist/slider/styled.js': 150,
  'dist/slider/a11y.js': 900,
  'dist/breadcrumb/index.js': 400,
  'dist/breadcrumb/styled.js': 150,
  'dist/breadcrumb/a11y.js': 550,
  'dist/tooltip/index.js': 300,
  'dist/tooltip/styled.js': 150,
  'dist/tooltip/a11y.js': 700,
  'dist/menu/index.js': 550,
  'dist/menu/styled.js': 200,
  'dist/menu/a11y.js': 1600,
}
// 18 a11y entries now (was 13): raised from 12000 to keep comparable
// headroom over the actual combined total.
const COMBINED = { 'all a11y entries': { max: 16000, match: /a11y\.js$/ } }
const CSS_BUDGET = 5000

const gz = (f) => gzipSync(readFileSync(join(root, f))).length
const rows = []
const errors = []

for (const [file, max] of Object.entries(BUDGETS)) {
  if (!existsSync(join(root, file))) continue // not built yet
  const size = gz(file)
  rows.push({ file, size, max })
  if (size > max) errors.push(`${file}: ${size} B gz exceeds budget ${max} B`)
}

for (const [label, { max, match }] of Object.entries(COMBINED)) {
  const files = rows.filter((r) => match.test(r.file))
  if (!files.length) continue
  const total = files.reduce((n, r) => n + r.size, 0)
  rows.push({ file: label, size: total, max })
  if (total > max) errors.push(`${label}: ${total} B gz exceeds budget ${max} B`)
}

if (existsSync(join(root, 'dist/styles.css'))) {
  const size = gz('dist/styles.css')
  rows.push({ file: 'dist/styles.css', size, max: CSS_BUDGET })
  if (size > CSS_BUDGET) errors.push(`dist/styles.css: ${size} B gz exceeds ${CSS_BUDGET} B`)
}

const md = [
  '# Bundle sizes',
  '',
  'Generated by `npm run build`. Gzipped, React external. Do not edit by hand.',
  '',
  '| Entry | Gzipped | Budget | |',
  '|---|---:|---:|---|',
  ...rows.map((r) => `| \`${r.file}\` | ${r.size} B | ${r.max} B | ${r.size <= r.max ? 'ok' : 'OVER'} |`),
  '',
].join('\n')

writeFileSync(join(root, 'SIZES.md'), md)
console.log(md)

if (errors.length) {
  console.error('\nsize budget FAILED:\n' + errors.map((e) => `  - ${e}`).join('\n') + '\n')
  process.exit(1)
}
